const cityNames = [
    "Aach (bei Trier)",
    "Aach (Hegau)",
    "Aachen",
    "Aalen",
    "Aarbergen",
    "Aasbüttel",
    "Abenberg",
    "Abensberg",
    "Abentheuer",
    "Absberg",
    "Abstatt",
    "Abtsbessingen",
    "Abtsgmünd",
    "Abtsteinach",
    "Abtswind",
    "Abtweiler",
    "Achberg",
    "Achern",
    "Achim",
    "Achslach",
    "Achstetten",
    "Acht",
    "Achtelsbach",
    "Achterwehr",
    "Achtrup",
    "Adelberg",
    "Adelebsen",
    "Adelheidsdorf",
    "Adelmannsfelden",
    "Adelschlag",
    "Adelsdorf",
    "Adelsheim",
    "Adelshofen (Mittelfranken)",
    "Adelshofen (Oberbayern)",
    "Adelsried",
    "Adelzhausen",
    "Adenau",
    "Adenbach",
    "Adenbüttel",
    "Adendorf",
    "Adlkofen",
    "Admannshagen-Bargeshagen",
    "Adorf/Vogtland",
    "Aebtissinwisch",
    "Aerzen",
    "Affalterbach",
    "Affing",
    "Affinghausen",
    "Affler",
    "Agathenburg",
    "Agethorst",
    "Aglasterhausen",
    "Aham",
    "Ahaus",
    "Ahausen",
    "Ahlbeck (Ueckermünder Heide)",
    "Ahlden (Aller)",
    "Ahlefeld-Bistensee",
    "Ahlen",
    "Ahlerstedt",
    "Ahlsdorf",
    "Ahlstädt",
    "Ahnatal",
    "Ahneby",
    "Ahnsbeck",
    "Ahnsen",
    "Aholfing",
    "Aholming",
    "Ahorn (Baden)",
    "Ahorn (Oberfranken)",
    "Ahorntal",
    "Ahrbrück",
    "Ahrensbök",
    "Ahrensburg",
    "Ahrensfelde",
    "Ahrenshagen-Daskow",
    "Ahrenshöft",
    "Ahrenshoop",
    "Ahrenviölfeld",
    "Ahrenviöl",
    "Aichach",
    "Aicha vorm Wald",
    "Aichelberg",
    "Aichen",
    "Aichhalden",
    "Aichstetten",
    "Aichtal",
    "Aichwald",
    "Aidenbach",
    "Aidhausen",
    "Aidlingen",
    "Aiglsbach",
    "Ailertchen",
    "Aindling",
    "Ainring",
    "Aislingen",
    "Aiterhofen",
    "Aitern",
    "Aitrach",
    "Aitrang",
    "Aken (Elbe)",
    "Aland (Altmark)",
    "Albaching",
    "Albbruck",
    "Albersdorf (Holstein)",
    "Albersdorf (Thüringen)",
    "Albershausen",
    "Albersweiler",
    "Albertshofen",
    "Albessen",
    "Albig",
    "Albisheim (Pfrimm)",
    "Albsfelde",
    "Albstadt",
    "Aldenhoven",
    "Aldersbach",
    "Aldingen",
    "Alerheim",
    "Alesheim",
    "Aletshausen",
    "Alf",
    "Alfdorf",
    "Alfeld (Leine)",
    "Alfeld (Mittelfranken)",
    "Alfhausen",
    "Alflen",
    "Alfstedt",
    "Alfter",
    "Algermissen",
    "Alheim",
    "Alken",
    "Alkersleben",
    "Alkersum",
    "Allenbach",
    "Allendorf (Eder)",
    "Allendorf (Lumda)",
    "Allendorf (Rheinland-Pfalz)",
    "Allendorf (Thüringen)",
    "Allenfeld",
    "Allensbach",
    "Allersberg",
    "Allershausen",
    "Alleshausen",
    "Alling",
    "Allmannshofen",
    "Allmannsweiler",
    "Allmendingen",
    "Allmersbach im Tal",
    "Allstedt",
    "Almdorf",
    "Almersbach",
    "Almstedt",
    "Alpen",
    "Alpenrod",
    "Alperstedt",
    "Alpirsbach",
    "Alsbach",
    "Alsbach-Hähnlein",
    "Alsdorf (Aachen)",
    "Alsdorf (Eifel)",
    "Alsdorf (Westerwald)",
    "Alsenz",
    "Alsfeld",
    "Alsheim",
    "Alsleben (Saale)",
    "Alt Bennebek",
    "Alt Bukow",
    "Altdöbern",
    "Altdorf (Kreis Böblingen)",
    "Altdorf (Kreis Esslingen)",
    "Altdorf (Niederbayern)",
    "Altdorf (Pfalz)",
    "Altdorf bei Nürnberg",
    "Alt Duvenstedt",
    "Altefähr",
    "Alteglofsheim",
    "Altena",
    "Altenahr",
    "Altenau",
    "Altenbamberg",
    "Altenbeken",
    "Altenberg",
    "Altenberga",
    "Altenberge",
    "Altenbeuthen",
    "Altenbuch",
    "Altenburg",
    "Altendiez",
    "Altendorf (Oberfranken)",
    "Altendorf (Oberpfalz)",
    "Altenglan",
    "Altenhagen",
    "Altenhausen",
    "Altenhof (Eckernförder Bucht)",
    "Altenhof (Mecklenburg)",
    "Altenholz",
    "Altenkirchen (Pfalz)",
    "Altenkirchen (Rügen)",
    "Altenkirchen (Westerwald)",
    "Altenkrempe",
    "Altenkunstadt",
    "Altenmarkt an der Alz",
    "Altenmedingen",
    "Altenmoor",
    "Altenmünster",
    "Altenpleen",
    "Altenriet",
    "Altenstadt (Wetterau)",
    "Altenstadt (Iller)",
    "Altenstadt (Oberbayern)",
    "Altenstadt an der Waldnaab",
    "Altensteig",
    "Altenthann",
    "Altentreptow",
    "Alterkülz",
    "Altertheim",
    "Altfraunhofen",
    "Althegnenberg",
    "Altheim (Alb)",
    "Altheim (Ehingen)",
    "Altheim (Riedlingen)",
    "Althengstett",
    "Althornbach",
    "Althütte",
    "Althüttendorf",
    "Altkalen",
    "Alt Krenzlin",
    "Altlandsberg",
    "Altlay",
    "Altleiningen",
    "Altlußheim",
    "Altmärkische Höhe",
    "Altmärkische Wische",
    "Altmannstein",
    "Alt Meteln",
    "Altmittweida",
    "Alt Mölln",
    "Altötting",
    "Altomünster",
    "Altrich",
    "Altrip",
    "Altscheid",
    "Alt Schwerin",
    "Altshausen",
    "Altstrimmig",
    "Alt Sührkow",
    "Alt Tellin",
    "Alt Tucheband",
    "Altusried",
    "Altwarp",
    "Altweidelbach",
    "Altwigshagen",
    "Alt Zachun",
    "Alt Zauche-Wußwerk",
    "Alveslohe",
    "Alzenau (in Unterfranken)",
    "Alzey",
    "Amberg (Oberpfalz)",
    "Amberg (Unterallgäu)",
    "Amelinghausen",
    "Amerang",
    "Amerdingen",
    "Am Großen Bruch",
    "Ammeldingen an der Our",
    "Ammeldingen bei Neuerburg",
    "Am Mellensee",
    "Ammerbuch",
    "Ammerndorf",
    "Ammersbek",
    "Ammerthal",
    "Amöneburg",
    "Am Ohmberg",
    "Amorbach",
    "Ampfing",
    "Am Salzhaff",
    "Amstetten",
    "Amt Creuzburg",
    "Amt Neuhaus",
    "Amtsberg",
    "Amt Wachsenburg",
    "Amtzell",
    "Andechs",
    "Anderlingen",
    "Andernach",
    "An der Poststraße",
    "An der Schmücke",
    "Andervenne",
    "Andisleben",
    "Angelbachtal",
    "Angelburg",
    "Anger",
    "Angermünde",
    "Angern",
    "Anhausen",
    "Ankershagen",
    "Anklam",
    "Ankum",
    "Annaberg-Buchholz",
    "Annaburg",
    "Annweiler am Trifels",
    "Anrode",
    "Anröchte",
    "Ansbach",
    "Anschau",
    "Antdorf",
    "Antrifttal",
    "Antweiler",
    "Anzing",
    "Apelern",
    "Apen",
    "Apenburg-Winterfeld",
    "Apensen",
    "Apfeldorf",
    "Apfeltrach",
    "Apolda",
    "Appel",
    "Appen",
    "Appenheim",
    "Appenweier",
    "Arbach",
    "Arberg",
    "Aremberg",
    "Arendsee",
    "Arenrath",
    "Arenshausen",
    "Aresing",
    "Arft",
    "Argenbühl",
    "Argenschwang",
    "Argenthal",
    "Arholzen",
    "Arkebek",
    "Arlewatt",
    "Armsheim",
    "Armstedt",
    "Armstorf",
    "Arnbruck",
    "Arneburg",
    "Arnis",
    "Arnsberg",
    "Arnschwang",
    "Arnsdorf",
    "Arnshöfen",
    "Arnstadt",
    "Arnstein (Sachsen-Anhalt)",
    "Arnstein (Unterfranken)",
    "Arnstorf",
    "Arpsdorf",
    "Arrach",
    "Artern",
    "Artlenburg",
    "Arzbach",
    "Arzberg (Oberfranken)",
    "Arzberg (Sachsen)",
    "Arzfeld",
    "Asbach (Hunsrück)",
    "Asbach (Westerwald)",
    "Asbach-Bäumenheim",
    "Asbach-Sickenberg",
    "Ascha",
    "Aschaffenburg",
    "Aschau am Inn",
    "Aschau im Chiemgau",
    "Aschbach",
    "Ascheberg (Holstein)",
    "Ascheberg (Münsterland)",
    "Ascheffel",
    "Aschersleben",
    "Aschheim",
    "Asendorf (Bruchhausen-Vilsen)",
    "Asendorf (Nordheide)",
    "Aspach",
    "Asperg",
    "Aspisheim",
    "Assamstadt",
    "Asselfingen",
    "Aßlar",
    "Aßling",
    "Astert",
    "Attendorn",
    "Attenhausen",
    "Attenhofen",
    "Attenkirchen",
    "Attenweiler",
    "Atting",
    "Atzelgift",
    "Au (Breisgau)",
    "Au am Rhein",
    "Aub",
    "Aubstadt",
    "Auderath",
    "Aue-Bad Schlema",
    "Auel",
    "Auen",
    "Auengrund",
    "Auenwald",
    "Auerbach (Erzgebirge)",
    "Auerbach (Niederbayern)",
    "Auerbach in der Oberpfalz",
    "Auerbach/Vogtland",
    "Auetal",
    "Aufhausen",
    "Aufseß",
    "Auggen",
    "Augsburg",
    "Augustdorf",
    "Augustusburg",
    "Auhagen",
    "Auhausen",
    "Au in der Hallertau",
    "Aukrug",
    "Aulendorf",
    "Aull",
    "Auma-Weidatal",
    "Aumühle",
    "Aura an der Saale",
    "Aurach",
    "Aurachtal",
    "Aura im Sinngrund",
    "Aurich",
    "Ausacker",
    "Ausleben",
    "Außernzell",
    "Auufer",
    "Auw an der Kyll",
    "Auw bei Prüm",
    "Aventoft",
    "Averlak",
    "Axstedt",
    "Aying",
    "Ayl",
    "Aystetten"
]
